### ISSUE TITLE
unable to set name

### ISSUE THREAD

**Issue by dtaylor-sfdc** [varnish/newrelic_varnish_plugin#13]
I have the following in my configuration file:

```
newrelic:
  license_key: 'blahblahblah'
  verbose: 1

agents:
  varnish:
    -
      name: '(Prod) Varnish'
```

and yet the name is always "varnish[default]".

As far as I can tell, this code isn't picking up the name in the configuration file:

```
    agent_human_labels("Varnish") { "#{@name||"varnish"}[#{@vname||"default"}]"}
```

Any idea how to fix this?  We have multiple environments running multiple instances of Varnish and I want to be able to distinguish between each environment.

Cheers!
